version: '3.7'
services:

  webrtc-proxy:
    container_name: webrtc-proxy
    build:
      context: docker/webrtc-proxy
      dockerfile: Dockerfile
    network_mode: host
#    environment:
#      - GIN_MODE=release
#    entrypoint: ["/bin/bash", "-c", "cd /application/media-server-go-demo/webrtc-to-rtmp && ./webrtc-to-rtmp"]
    volumes:
      - ./:/application/:rw
